name: ci

on: [push, pull_request]

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-13
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo check
        run: cargo check

      - name: Run cargo test
        run: |
          cd test-exe
          cargo build --release
          cd ..
          cargo test -- --nocapture
